### ISSUE TITLE
[Bug] Download arrow is off center + spinners reset after every page

### ISSUE THREAD

**Issue by KraXen72** [CrepeTF/Takoyomi#2]
![alt](https://cdn.discordapp.com/attachments/538734863977676803/814063928383373322/Screenshot_20210224-101918_SY_Comics.png)

+ also when the download proceeds by a page, the queued spinners reset their animation (this one is also a bug in normal sy)

## Device information
* Tachiyomi version: latest sy comics
* Android version: 11
* Device: samsung galaxy m21

## Steps to reproduce
1. start downloading anything
2. look at arrow

### Expected behavior
arrow should be centered.
spinners shouldn't reset their animation every time the download proceeds

**Comment by CrepeTF** [comment]
The animation reset is an issue with stable so I won't be fixing that, otherwise the rest can be fixed
