### ISSUE TITLE
crash upon clicking on reading button from history

### ISSUE THREAD

**Issue by HikaruIchijyo** [CrepeTF/Takoyomi#31]
### Steps to reproduce

Go to history select on any manga open it click on resume button to start reading>>boom crashes

### Expected behavior

Should open reader

### Actual behavior

Crashes

### Crash logs

--------- beginning of crash
04-08 04:46:18.841 30556 30556 E AndroidRuntime: FATAL EXCEPTION: main
04-08 04:46:18.841 30556 30556 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy.crepe, PID: 30556
04-08 04:46:18.841 30556 30556 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'int androidx.recyclerview.widget.AdapterHelper$UpdateOp.cmd' on a null object reference
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.getAdapterPositionInRecyclerView(RecyclerView.java:6)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$ViewHolder.getBindingAdapterPosition(RecyclerView.java:4)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$ViewHolder.getAdapterPosition(RecyclerView.java:1)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at eu.davidea.viewholders.ContentViewHolder.getFlexibleAdapterPosition(ContentViewHolder.java:1)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at eu.davidea.viewholders.FlexibleViewHolder.toggleActivation(FlexibleViewHolder.java:1)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at eu.davidea.flexibleadapter.SelectableAdapter.notifySelectionChanged(SelectableAdapter.java:2)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at eu.davidea.flexibleadapter.SelectableAdapter.clearSelection(SelectableAdapter.java:8)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at eu.davidea.flexibleadapter.FlexibleAdapter.clearSelection(FlexibleAdapter.java:2)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.manga.MangaController.onDestroyActionMode(MangaController.kt:2)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at eu.kanade.tachiyomi.widget.ActionModeWithToolbar$actionModeCallback$1.onDestroyActionMode(ActionModeWithToolbar.kt:1)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onDestroyActionMode(AppCompatDelegateImpl.java:1)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at androidx.appcompat.view.StandaloneActionMode.finish(StandaloneActionMode.java:3)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at eu.kanade.tachiyomi.widget.ActionModeWithToolbar.finish(ActionModeWithToolbar.kt:1)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.manga.MangaController.destroyActionModeIfNeeded(MangaController.kt:3)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.manga.MangaController.deleteChapters(MangaController.kt:4)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.manga.MangaController.deleteChapters(MangaController.kt:1)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.manga.chapter.DeleteChaptersDialog.onCreateDialog$lambda-0(DeleteChaptersDialog.kt:1)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.manga.chapter.DeleteChaptersDialog.$r8$lambda$aB2o-Ca1Gcei2DySNY0miAOY-EU(Unknown Source:0)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.manga.chapter.DeleteChaptersDialog$$ExternalSyntheticLambda0.onClick(Unknown Source:10)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:3)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8031)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
04-08 04:46:18.841 30556 30556 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
--------- beginning of system
--------- beginning of main
04-10 21:57:22.991 11228 11286 E FrameEvents: updateAcquireFence: Did not find frame.
04-10 21:57:23.074 11228 11228 E AndroidRuntime: FATAL EXCEPTION: main
04-10 21:57:23.074 11228 11228 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy.crepe, PID: 11228
04-10 21:57:23.074 11228 11228 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.kanade.tachiyomi.sy.crepe/eu.kanade.tachiyomi.ui.reader.ReaderActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable$ConstantState android.graphics.drawable.Drawable.getConstantState()' on a null object reference
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3564)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3736)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8031)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable$ConstantState android.graphics.drawable.Drawable.getConstantState()' on a null object reference
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.initializeMenu(ReaderActivity.kt:50)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.onCreate(ReaderActivity.kt:25)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8142)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8114)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3537)
04-10 21:57:23.074 11228 11228 E AndroidRuntime: 	... 11 more
04-10 21:57:25.483 12962 12962 E hiyomi.sy.crep: Not starting debugger since process cannot load the jdwp agent.
04-10 21:57:25.595 12962 12962 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: Settings request failed.
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: java.net.ConnectException: Failed to connect to firebase-settings.crashlytics.com/0.0.0.0:443
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:302)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.network.HttpGetRequest.execute(HttpGetRequest.java:11)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:18)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@18.0.1:3)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:1)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:2)
04-10 21:57:25.628 12962 12999 E FirebaseCrashlytics: 	at java.lang.Thread.run(Thread.java:923)
04-10 21:57:25.998 12962 13029 E SQLiteLog: (284) automatic index on C(manga_id)
04-10 21:57:25.998 12962 13029 E SQLiteLog: (284) automatic index on R(manga_id)
04-10 21:57:25.998 12962 13029 E SQLiteLog: (284) automatic index on C(merge_id)
04-10 21:57:25.998 12962 13029 E SQLiteLog: (284) automatic index on R(merge_id)
04-10 21:57:25.998 12962 13029 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
04-10 21:57:26.337 12962 13067 E ion     : ioctl c0044901 failed with code -1: Invalid argument
04-10 21:57:26.337 12962 13064 E ion     : ioctl c0044901 failed with code -1: Invalid argument
04-10 21:57:26.340 12962 13067 E libc    : Access denied finding property "vendor.debug.drm.logv"
04-10 21:57:26.340 12962 13067 E libc    : Access denied finding property "vendor.debug.drm.logv"
04-10 21:57:26.340 12962 13067 E libc    : Access denied finding property "vendor.debug.drm.logd"
04-10 21:57:26.340 12962 13067 E libc    : Access denied finding property "vendor.debug.drm.logv"
04-10 21:57:26.347 12962 13065 E ion     : ioctl c0044901 failed with code -1: Invalid argument
App version: 3.1.8 (standard, ca5005e50, 43, 2022-04-10T16:31Z)
Preview build: 0
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.011
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: secret
Device model: M2101K7BG
Device product name: secret_global

### Tachiyomi version

3.18

### Android version

11

### Device

redmi note 10s

### Other details

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.1](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
New build with patch soon

**Comment by HikaruIchijyo** [comment]
> New build with patch soon

Thanks.
Btw crashes everywhere not just history
