### ISSUE TITLE
some suggestions for design

### ISSUE THREAD

**Issue by HikaruIchijyo** [CrepeTF/Takoyomi#35]
### Describe your suggested feature

1. If manga is not added to library and when u selwct chapters to download a pop up appears it kinda covers whole toolbar fr a while(that add the manga to library one) then u either need to add it to library or w8 maybe some design changes so it wont cover the bottom toolbar or something like.
![Screenshot_2022-05-14-10-34-47-704_eu kanade tachiyomi sy crepe](https://user-images.githubusercontent.com/38470944/168412258-33c8128f-d06f-4253-b2ec-c71de3ae59ab.jpg)

2. If u remove manga from library a popup comes(to delete downloaded chapters even though all chapters are deleted previously same changes like above.

3. There is a bulk download notification which persists untill u remove it manually or something. Maybe change it to popup and hide after few seconds or somethings.

It is main tachi design still it would be good fr tako.

If any of these suggestions are accepted approveable i can open seperate ticket fr them

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.8.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
1. You can swipe away the snackbar

2. You can swipe away the snackbar

3. Not sure which one you're talking about

**Comment by HikaruIchijyo** [comment]
> 1. You can swipe away the snackbar
> 
> 2. You can swipe away the snackbar
> 
> 3. Not sure which one you're talking about

About 1 & 2 thanks i didnt know about that.

About 3 i will send ss

**Comment by HikaruIchijyo** [comment]
> 3. Not sure which one you're talking about

They were 70 chapters

![Screenshot_2022-05-20-14-15-59-415_eu.kanade.tachiyomi.sy.crepe.jpg](https://user-images.githubusercontent.com/38470944/169496611-884aa36f-a129-4acc-ad55-f7f94627e9d9.jpg)

**Comment by CrepeTF** [comment]
I will not be changing that, downloading 70 chapters is still a lot since Tachiyomi was not designed to be a mass downloader. If you want that changed you will have to request it for main Tachiyomi

**Comment by HikaruIchijyo** [comment]
> I will not be changing that, downloading 70 chapters is still a lot since Tachiyomi was not designed to be a mass downloader. If you want that changed you will have to request it for main Tachiyomi

Ah thanks no issues
