### ISSUE TITLE
New UI break Search oneclick Title

### ISSUE THREAD

**Issue by e-shl** [CrepeTF/Takoyomi#36]
### Steps to reproduce

1. Open Manga details 
2.  Click on Title

### Expected behavior

Global Search

### Actual behavior

NO Global Search (or opening the full title)

### Tachiyomi version

3.2.4

### Android version

AOSP10

### Device

Mi9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Long tap webview button
