### ISSUE TITLE
crashing on A11 tablet

### ISSUE THREAD

**Issue by notquite28** [CrepeTF/Takoyomi#40]
### Steps to reproduce

Updated to 3.2.5 from 3.2.4 and then the app failed to launch and keeps crashing after splash screen. 

### Expected behavior

App V3.2.5 should launch 

### Actual behavior

App doesn't launch whereas 3.2.4 launches as expected 

### Tachiyomi version

3.2.5

### Android version

Android 11

### Device

realme pad

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.2](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghost** [comment]
same here app got crashed

**Comment by CrepeTF** [comment]
Will release a fix soon
