### ISSUE TITLE
[Feature Request] Search bar in throughout the app

### ISSUE THREAD

**Issue by joseph619** [CrepeTF/Takoyomi#7]
As per mockup, replace the magnifying glass icon with a search bar wherever possible (reasonably)

**Comment by CrepeTF** [comment]
https://github.com/Jays2Kings/tachiyomiJ2K/commit/2d520026a13d9182b589b31900eb71c95219721d

**Comment by CrepeTF** [comment]
https://github.com/CrepeTF/SY-Comics/tree/search-bar

**Comment by CrepeTF** [comment]
@joseph619 
https://github.com/CrepeTF/Takoyomi/releases/latest

**Comment by joseph619** [comment]
Seems to be missing for global search screen in Browse, but otherwise good job 👀

**Comment by CrepeTF** [comment]
> Seems to be missing for global search screen in Browse, but otherwise good job 👀 

Yeah it'll take a bit more time to makes it work in browse due to the tabs
